### Create Task
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "id": "uuid",
  "title": "SAFSDFSDFSDF",
  "description": "jooSDFSDFSDFSDoo",
  "completed": false,
  "createdAt": "2026-02-14T16:00:00.000Z"
}

### Get All Tasks
GET http://localhost:3000/tasks

### Get Task by ID
@taskId = 69c7e9aa-8b5c-407b-908a-bc4c99ddf57e
GET http://localhost:3000/tasks/{{taskId}}

### Update Task (Partial)
PATCH http://localhost:3000/tasks/{{taskId}}
Content-Type: application/json

{
  "completed": false,
  "description": "p34RSDFDFaaaaaaaaaaDF"
}

### Delete Task
DELETE http://localhost:3000/tasks/{{taskId}}
