
@baseUrl = http://localhost:3000/tasks

### Get all tasks
GET {{baseUrl}}
Content-Type: application/json

### Get task by ID
GET {{baseUrl}}/1
Accept: application/json

### Create a task
POST {{baseUrl}}
Content-Type: application/json

{
  "title": "Test Task 1",
  "description": "This is a test task"
}
### Create another task
POST {{baseUrl}}
Content-Type: application/json

{
  "title": "Another Task",
  "description": "Second test task"
}

### Update a task
PATCH  {{baseUrl}}/1
Content-Type: application/json

{
  "title": "Updated Task 1",
  "completed": true
}

### Update a task partially
PATCH {{baseUrl}}/2
Content-Type: application/json

{
  "description": "Updated description only"
}

### 7️⃣ Delete a task
DELETE {{baseUrl}}/1
Accept: application/json

### 8️⃣ Verify deletion
GET {{baseUrl}}/1
Accept: application/json



